// SPDX-License-Identifier: GPL-3.0-or-later

//! Sliding-piece attacks by magic bitboards. **Magics are the only path.** There is no PEXT
//! variant and no cargo feature for one: `_pext_u64` cannot be called from safe code, and this
//! crate is `#![forbid(unsafe_code)]`.

use crate::bitboard::Bitboard;
use crate::types::Square;

// ---------------------------------------------------------------------------
// The magic numbers
// ---------------------------------------------------------------------------
// Regenerate with `cargo run --release -p cadence-tools -- magics [seed]` and paste the output
// over this block. Any valid set works; this one is kept so the tables (and everything
// downstream that depends on iteration order over them, which today is nothing) are a function
// of the repository.

// Generated by `cadence-tools magics 0x00CADE7CE5EED001`. Plain magics, shift = 64 -
// popcount(mask); rook table 102400 entries, bishop table 5248.
#[rustfmt::skip]
const ROOK_MAGIC_NUMBERS: [u64; 64] = [
    0x0900108000402100, 0x4040004010002004, 0x0200082210420180, 0x2880080082041000,
    0x1880020400800800, 0x03000814000A0100, 0x1080010002004080, 0x4080004080003100,
    0x8020800080400022, 0x0010401000402000, 0x8804802000100582, 0x8000808010000800,
    0x0C83000800310004, 0x2200800200040080, 0x1284000448011042, 0x8202002100440092,
    0x0000808000400020, 0x8090004000402008, 0x0090002020080400, 0x0006420008220012,
    0x1000828004000800, 0x0018808004000200, 0x6800840018024110, 0x8020020018810844,
    0x1110400080208000, 0x6021078E00204200, 0x4020080040401000, 0x0008002101001000,
    0x0100040080800800, 0x0000040080020080, 0x20A0010080800200, 0x8400802080004100,
    0x0040004032800088, 0x0000402000401000, 0x4002200088801000, 0x0080801002800800,
    0x0052180082801400, 0x1000020080800400, 0x4000010284000810, 0x100100508200090C,
    0x0044804000228000, 0x2010402010004000, 0x094102A000430011, 0x0882002008420011,
    0x0041001008010004, 0x0041000804010002, 0x000C094288040030, 0x602801026282000C,
    0x0200810030460600, 0x00C0002010080020, 0xC000200010008080, 0x4200800800100080,
    0x4010800400080280, 0xA002004904302200, 0x021042102108A400, 0x1010050040840600,
    0x0420800021001041, 0x0000201040008901, 0x88202002A8510041, 0x0001042010010009,
    0x300F000402100801, 0x1009000218040003, 0x0000101801408204, 0x8000008020410402,
];
#[rustfmt::skip]
const BISHOP_MAGIC_NUMBERS: [u64; 64] = [
    0x0010020801240010, 0x00C4B08082008000, 0x0004042092000200, 0x2951040080000818,
    0x0102021000410040, 0x1802021004181000, 0x4404043402888030, 0x2014144104202080,
    0x0000400428020046, 0x0000044480940100, 0x0000044122020000, 0x0002180685040112,
    0x0005020210041004, 0x8240284442200200, 0x0888004808080A82, 0x4010004430880800,
    0x18400020220A4600, 0x0A90012042208100, 0x060408080044000C, 0x260D2004040080A0,
    0x0034200202010402, 0x0088A00110101000, 0x002400020A120200, 0x00A0810202010108,
    0x024A4001101C08A1, 0x8082A00010040088, 0x0118080004002820, 0x8401080024020420,
    0xA065004509004000, 0x0001C34002011000, 0x082104020842082C, 0x0004004210804400,
    0x081044C442200800, 0x0085049004200750, 0x0302002220100086, 0x1021040400880120,
    0x2204210010140040, 0x0248101040048800, 0x02108221840C4400, 0x0401104200448200,
    0x500401041048C000, 0xD42413C410002400, 0x80000A0090000200, 0x089029A081220800,
    0x1400421040400400, 0x000411004D02E200, 0x40621004048A0108, 0x0002580843101080,
    0x0021080804841000, 0x0002010108022000, 0x1601110080908004, 0x2000251484040280,
    0x00C081A020410009, 0x4800102081010401, 0x0089200104010800, 0x0A10100120408064,
    0x8002030401042274, 0x10005212020D0C02, 0x002800410C112401, 0x0008080208208805,
    0x8880020004208200, 0x2000061004102420, 0x2040840404180A01, 0x202008020C504200,
];

// ---------------------------------------------------------------------------
// Geometry, in a form const evaluation can run
// ---------------------------------------------------------------------------

/// Rook and bishop directions as `(file delta, rank delta)`.
const ROOK_DIRS: [(i32, i32); 4] = [(1, 0), (-1, 0), (0, 1), (0, -1)];
const BISHOP_DIRS: [(i32, i32); 4] = [(1, 1), (1, -1), (-1, 1), (-1, -1)];

/// The bit for `(file, rank)`, or `None` off the board.
const fn bit_at(file: i32, rank: i32) -> Option<u64> {
    if file < 0 || file > 7 || rank < 0 || rank > 7 {
        None
    } else {
        Some(1u64 << (rank * 8 + file))
    }
}

/// Attacks from square index `sq` under `occ`: each direction walked to the edge, the first
/// occupied square included.
pub(crate) const fn slow_attacks(sq: u8, occ: u64, dirs: &[(i32, i32); 4]) -> u64 {
    let (f0, r0) = ((sq % 8) as i32, (sq / 8) as i32);
    let mut out = 0u64;
    let mut d = 0;
    while d < 4 {
        let (df, dr) = dirs[d];
        let (mut f, mut r) = (f0 + df, r0 + dr);
        while let Some(b) = bit_at(f, r) {
            out |= b;
            if occ & b != 0 {
                break;
            }
            f += df;
            r += dr;
        }
        d += 1;
    }
    out
}

/// The relevant occupancy for `sq`: the empty-board rays minus their last square in each
/// direction, since a blocker on the edge changes nothing.
const fn relevant_mask(sq: u8, dirs: &[(i32, i32); 4]) -> u64 {
    let (f0, r0) = ((sq % 8) as i32, (sq / 8) as i32);
    let mut out = 0u64;
    let mut d = 0;
    while d < 4 {
        let (df, dr) = dirs[d];
        let (mut f, mut r) = (f0 + df, r0 + dr);
        while bit_at(f + df, r + dr).is_some() {
            if let Some(b) = bit_at(f, r) {
                out |= b;
            }
            f += df;
            r += dr;
        }
        d += 1;
    }
    out
}

// ---------------------------------------------------------------------------
// Tables
// ---------------------------------------------------------------------------

/// The one place occupancy becomes a table index. `((occ & mask) * magic) >> shift`.
#[inline]
#[must_use]
const fn slider_hash(occ: u64, mask: u64, magic: u64, shift: u32) -> usize {
    ((occ & mask).wrapping_mul(magic) >> shift) as usize
}

/// Per-square lookup parameters. `offset` is where this square's `1 << bits` slots begin in the
/// shared table.
#[derive(Clone, Copy)]
struct Magic {
    mask: u64,
    multiplier: u64,
    shift: u32,
    offset: usize,
}

const fn build_magics(numbers: &[u64; 64], dirs: &[(i32, i32); 4]) -> [Magic; 64] {
    let mut out = [Magic {
        mask: 0,
        multiplier: 0,
        shift: 0,
        offset: 0,
    }; 64];
    let mut offset = 0usize;
    let mut sq = 0;
    while sq < 64 {
        let mask = relevant_mask(sq as u8, dirs);
        let bits = mask.count_ones();
        out[sq] = Magic {
            mask,
            multiplier: numbers[sq],
            shift: 64 - bits,
            offset,
        };
        offset += 1 << bits;
        sq += 1;
    }
    out
}

const fn table_size(magics: &[Magic; 64]) -> usize {
    let last = magics[63];
    last.offset + (1 << (64 - last.shift))
}

/// Fill the table: for every square, every subset of its mask, by the carry-rippler. An attack
/// set is never empty, so a zero slot is an unwritten one, and a written slot that disagrees is
/// a magic collision, which is a compile-time panic here, not a runtime surprise.
const fn build_table<const N: usize>(magics: &[Magic; 64], dirs: &[(i32, i32); 4]) -> [u64; N] {
    let mut table = [0u64; N];
    let mut sq = 0;
    while sq < 64 {
        let m = magics[sq];
        let mut occ = 0u64;
        loop {
            let attacks = slow_attacks(sq as u8, occ, dirs);
            let idx = m.offset + slider_hash(occ, m.mask, m.multiplier, m.shift);
            assert!(
                table[idx] == 0 || table[idx] == attacks,
                "magic collision: two occupancies map to one slot with different attacks"
            );
            table[idx] = attacks;
            occ = occ.wrapping_sub(m.mask) & m.mask;
            if occ == 0 {
                break;
            }
        }
        sq += 1;
    }
    table
}

const ROOK_MAGICS: [Magic; 64] = build_magics(&ROOK_MAGIC_NUMBERS, &ROOK_DIRS);
const BISHOP_MAGICS: [Magic; 64] = build_magics(&BISHOP_MAGIC_NUMBERS, &BISHOP_DIRS);

const ROOK_TABLE_SIZE: usize = table_size(&ROOK_MAGICS);
const BISHOP_TABLE_SIZE: usize = table_size(&BISHOP_MAGICS);

// Plain magics with shift = 64 - popcount(mask) have exactly these sizes.
const _: () = assert!(ROOK_TABLE_SIZE == 102_400);
const _: () = assert!(BISHOP_TABLE_SIZE == 5_248);

// `long_running_const_eval` is deny-by-default: rustc stops a constant evaluation that exceeds
// its step budget on the assumption that it is an accidental `loop {}`. Filling 107,648 slots,
// each with a ray-walk, is a deliberately long evaluation, and this attribute says so.
#[allow(long_running_const_eval)]
static ROOK_TABLE: [u64; ROOK_TABLE_SIZE] = build_table(&ROOK_MAGICS, &ROOK_DIRS);
#[allow(long_running_const_eval)]
static BISHOP_TABLE: [u64; BISHOP_TABLE_SIZE] = build_table(&BISHOP_MAGICS, &BISHOP_DIRS);

// ---------------------------------------------------------------------------
// Lookups
// ---------------------------------------------------------------------------

/// Squares a rook on `sq` attacks under `occ`, the first blocker in each direction included.
#[inline]
#[must_use]
pub(crate) fn rook_attacks(sq: Square, occ: Bitboard) -> Bitboard {
    let m = &ROOK_MAGICS[sq.index()];
    Bitboard(ROOK_TABLE[m.offset + slider_hash(occ.0, m.mask, m.multiplier, m.shift)])
}

/// Squares a bishop on `sq` attacks under `occ`, the first blocker in each direction included.
#[inline]
#[must_use]
pub(crate) fn bishop_attacks(sq: Square, occ: Bitboard) -> Bitboard {
    let m = &BISHOP_MAGICS[sq.index()];
    Bitboard(BISHOP_TABLE[m.offset + slider_hash(occ.0, m.mask, m.multiplier, m.shift)])
}
