# SPDX-License-Identifier: GPL-3.0-or-later
# A site bound to one host address must not start before ifupdown has assigned
# that address. network-online.target alone can be reached before that point.
[Unit]
After=networking.service
Wants=networking.service

[Service]
Restart=on-failure
RestartSec=3
